name: Build Poky

on: workflow_dispatch

jobs:
  build:
    # this can be assigned to a more powerful runner to improve build time
    runs-on: self-hosted

    # use the builder container
    container: 
      image: ghcr.io/${{ github.repository_owner }}/yoctoresearch/yocto-builder:latest
      options: --user root
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

        
      - name: Debug
        shell: bash
        run: |
          echo "Current workspace: $GITHUB_WORKSPACE"
          ls -alh $GITHUB_WORKSPACE
          source oe-init-build-env build
          echo "Setup build"
          ls -alh $GITHUB_WORKSPACE/build
        
      - name: Change Ownership of the Workspace
        run: |
          chown -R builder:builder $GITHUB_WORKSPACE

      # Cache the downloads and sstate-cache directories
      - name: Download cache as artifact
        uses: actions/download-artifact@v4
        with:
          name: yocto-cache
          path: |
            $GITHUB_WORKSPACE/build
        continue-on-error: true

      - name: Debug-2
        shell: bash
        run: |
          echo "Setup build"
          ls -alh $GITHUB_WORKSPACE/build

      # build the image
      - name: Build
        shell: bash
        run: |
          su - builder -c "
            cd $GITHUB_WORKSPACE
            source oe-init-build-env build
            bitbake core-image-minimal
          "

      - name: Debug-3
        shell: bash
        run: |
          echo "Setup build"
          ls -alh $GITHUB_WORKSPACE/build
        # sleep 120m

      # Cache the downloads and sstate-cache directories
      - name: Upload cache as artifact
        uses: actions/upload-artifact@v4
        with:
          name: yocto-cache
          path: |
            $GITHUB_WORKSPACE/build/downloads
            $GITHUB_WORKSPACE/build/sstate-cache

      # save the image by uploading artifact
      - name: Save Image
        uses: actions/upload-artifact@v4
        with:
          name: yocto-images
          path: |
            $GITHUB_WORKSPACE/build/tmp/deploy/images/qemux86-64
            
