name: Build Poky

on: workflow_dispatch

jobs:
  build:
    # this can be assigned to a more powerful runner to improve build time
    runs-on: self-hosted

    # use the builder container
    container: 
      image: ghcr.io/${{ github.repository_owner }}/yoctoresearch/yocto-builder:latest
      options: --user root
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

        
      - name: Debug
        shell: bash
        run: |
          echo "Current workspace: ${{ github.workspace }}"
          ls -alh ${{ github.workspace }}
          source oe-init-build-env build
          echo "Setup build"
          ls -alh ${{ github.workspace }}/build
        
      - name: Change Ownership of the Workspace
        run: |
          chown -R builder:builder ${{ github.workspace }}

      # Cache the downloads and sstate-cache directories
      - name: Restore Yocto downloads and sstate-cache
        uses: actions/cache/restore@v4
        with:
          path: |
            ${{ github.workspace }}/build/downloads
            ${{ github.workspace }}/build/sstate-cache
          key: ${{ runner.os }}-yocto-cache

      - name: Debug-2
        shell: bash
        run: |
          echo "Setup build"
          ls -alh ${{ github.workspace }}/build

      # build the image
      - name: Build
        shell: bash
        run: |
          su - builder -c "
            cd ${{ github.workspace }}
            source oe-init-build-env build
            bitbake core-image-minimal
          "

      - name: Debug-3
        shell: bash
        run: |
          echo "Setup build"
          ls -alh ${{ github.workspace }}/build

      # Cache the downloads and sstate-cache directories
      - name: Save Yocto downloads and sstate-cache
        uses: actions/cache/save@v4
        with:
          path: |
            ${{ github.workspace }}/build/downloads
            ${{ github.workspace }}/build/sstate-cache
          key: ${{ runner.os }}-yocto-cache

      # save the image by uploading artifact
      - name: Save Image
        uses: actions/upload-artifact@v4
        with:
          name: yocto-images
          path: |
            ${{ github.workspace }}/build/tmp/deploy/images/qemux86-64
            
